#/************************************************
#* File: makefile.
#* Desc: Building definitions for the Plzen Common Components


include $(AKRAPROJ)/geneMake.lnx

subdirs=Core Spec

all: $(subdirs)
.PHONY: $(subdirs)

Core:
	cd $@ && $(MAKE)

Spec:
	cd $@ && $(MAKE)

clean:
	@for i in $(subdirs); do ( \
	    cd $$i && $(MAKE) clean \
	) \
	|| exit 1; done

